from Util.BDUtil import ConnectBD
from Module.Address.dao import AddressDao
from Module.Book.dao import BookDao
from Module.Author.dao import AuthorDao
from Module.Company.dao import CompanyDao 
from Module.Confiability.dao import ConfiabilityDao
from Module.Employee.dao import EmployeeDao
from Module.Loan.dao import LoanDao
from Module.Location.dao import LocationDao
from Module.Seal.dao import SealDao
from Module.User.dao import UserDao